services:
  - type: web
    name: aletone-api
    env: node
    repo: https://github.com/Juancho250/Aletone-B
    branch: main
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    autoDeployTrigger: checksPass
    healthCheckPath: /healthz
    maxShutdownDelaySeconds: 30
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 5
